# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/android'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = "GeoQuiz"
  app.package = "net.darinwilson.android.geoquiz"
  app.main_activity = "QuizActivity"
  app.theme = "@style/Theme.AppCompat.Light.DarkActionBar"
  app.archs = ["x86"] unless ARGV.include?("device") || ARGV.include?("release")
  app.gradle do
    dependency "com.android.support:appcompat-v7:22.1.0"
  end
end
